import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Info from "../components/Info";

export default function Home() {
    return (
        <div className='max-w-7xl mx-auto'>
            <Head>
                <title>Medium Blog</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Header />
            <Info />
        </div>
    );
}
