import Head from "next/head";
import Header from "../components/Header";
import Info from "../components/Info";
import Posts from "../components/Posts";
import { sanityClient } from "../sanity";
import { Post } from "../typings";

type Props = {
    posts: Post[];
};
export default function Home({ posts }: Props) {
    return (
        <div className='max-w-7xl mx-auto'>
            <Head>
                <title>Medium Blog</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Header />
            <Info />

            <Posts posts={posts} />
        </div>
    );
}

export const getServerSideProps = async () => {
    const query = `*[_type == "post"]{
        _id,
        title,
        description,
        mainImage,
        slug,
        author -> {
        name,
        image
        }
    }`;

    const posts = await sanityClient.fetch(query);

    return {
        props: { posts },
    };
};
